# Generated by Django 4.0.1 on 2022-01-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiket_id', models.IntegerField()),
                ('tiket_num', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('service_id', models.CharField(max_length=200)),
                ('service_name', models.CharField(max_length=200)),
                ('stand_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
