# Generated by Django 4.0.1 on 2022-01-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_tiket_id_tickets_ticket_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='stand_time',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='start_time',
        ),
    ]
