# Generated by Django 4.0.1 on 2022-01-14 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_tickets_stand_time_remove_tickets_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='stand_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
