# Generated by Django 4.0.1 on 2022-01-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_tickets_stand_time_tickets_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='service_id',
        ),
    ]
