# Generated by Django 4.0.1 on 2022-01-14 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_tickets_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='service_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
