# Generated by Django 4.0.1 on 2022-01-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_tickets_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
