# Generated by Django 4.0 on 2022-01-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_tickets_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='service_name',
            field=models.CharField(max_length=201),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
