# Generated by Django 3.2.7 on 2022-01-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_tickets_service_name_alter_tickets_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
