# Generated by Django 3.2.7 on 2022-01-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_tickets_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='user',
            new_name='user_name',
        ),
    ]
