# Generated by Django 3.2.7 on 2022-01-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_rename_user_tickets_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
