# Generated by Django 4.0.1 on 2022-01-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_tickets_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
