# Generated by Django 4.0.1 on 2022-01-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_tickets_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='wait_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
