# Generated by Django 4.0.1 on 2022-01-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_tickets_ticket_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='wait_time',
            new_name='waite_time',
        ),
    ]
