# Generated by Django 4.0.1 on 2022-01-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_rename_wait_time_tickets_waite_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='waite_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
