# Generated by Django 4.0.1 on 2022-01-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_alter_tickets_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='waite_time',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
