# Generated by Django 4.0.1 on 2022-01-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_tickets_start_time_alter_tickets_waite_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='waite_time',
            new_name='waite_stand_time',
        ),
        migrations.AddField(
            model_name='tickets',
            name='waite_start_time',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
