# Generated by Django 4.0.1 on 2022-01-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_rename_waite_time_tickets_waite_stand_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='waite_stand_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='waite_start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
